### PR TITLE
(Issue #80) Global molecules not gced

### LINKED ISSUE #80: onUnmount callback not triggered in nested components
## Description

A bug has been discovered in Bunshi where `onUnmount` of a molecule is not called when a component using that molecule is wrapped in another component that uses a different molecule.

## CodeSandbox Example

The bug is reproducible in [CodeSandbox](https://codesandbox.io/p/devbox/headless-river-p3d59z?file=%2FApp.tsx%3A11%2C3&workspaceId=ws_91WhgdDnCbm887nyuqDihj), which is based on the example from the [Bunshi documentation](https://www.bunshi.org/concepts/molecules/#onunmount):

```typescript
import { molecule, onMount } from "bunshi";
import { useMolecule } from "bunshi/react";
import { atom, useAtom } from "jotai";
import React, { useState } from "react";

export const TestMolecule = molecule(() => {
  return atom(0);
});

export const CountMolecule = molecule(() => {
  console.log("Created CountMolecule");
  onMount(() => {
    console.log("Mounted CountMolecule");
    return () => console.log("Unmounted CountMolecule");
  });
  return atom(0);
});

const TestProvider = ({ children }: any) => {
  /**** Comment this line, and you will see "Unmounted CountMolecule" in console ****/
  useMolecule(TestMolecule);

  return <div>{children}</div>;
};

const Counter = () => {
  const countAtom = useMolecule(CountMolecule);
  const [count, setCount] = useAtom(countAtom);

  return (
    <div>
      <p>Clicks: {count}</p>
      <button onClick={() => setCount((c) => c + 1)}>Increment</button>
    </div>
  );
};

const TempApp = () => {
  const [isMounted, setMounted] = useState(false);
  return (
    <div>
      Open your browser console to see the logs for lifecycle events.
      <hr />
      <button onClick={() => setMounted((x) => !x)}>
        {isMounted ? "Remove Counter" : "Load Counter"}
      </button>
      {isMounted && (
        <>
          <Counter />
          <Counter />
        </>
      )}
    </div>
  );
};

export default function App() {
  return (
    <>
      <TestProvider>
        <TempApp />
      </TestProvider>
    </>
  );
}
```

**Expected Console Output:**

```
Created CountMolecule
Mounted CountMolecule
Unmounted CountMolecule  // This should appear when removing the counter
```

**Actual Console Output:**

```
Created CountMolecule
Mounted CountMolecule
// Unmounted CountMolecule is NOT called when removing the counter
```

**Note:** If you comment out the `useMolecule(TestMolecule)` line in `TestProvider`, the `onUnmount` callback will work correctly.

## Steps to Reproduce

1. Open the CodeSandbox example
2. Open browser console
3. Click "Load Counter" to mount the Counter components
4. Click "Remove Counter" to unmount the Counter components
5. Observe that "Unmounted CountMolecule" is NOT logged in console

## Environment

- Bunshi: 2.1.5
- Jotai: 2.12.5
- React: ^18

## Unit Test

A test case for `src/react/useMolecule.test.tsx`:

```typescript
describe("Nested component lifecycle bug", () => {
  const outerMoleculeLifecycle = createLifecycleUtils();
  const innerMoleculeLifecycle = createLifecycleUtils();

  const OuterMolecule = molecule(() => {
    const value = "outer";
    outerMoleculeLifecycle.connect(value);
    return value;
  });

  const InnerMolecule = molecule(() => {
    const value = "inner";
    innerMoleculeLifecycle.connect(value);
    return value;
  });

  const OuterComponent = ({ children }: { children?: React.ReactNode }) => {
    const outerValue = useMolecule(OuterMolecule);
    return (
      <div data-testid="outer">
        <span>Outer: {outerValue}</span>
        {children}
      </div>
    );
  };

  const InnerComponent = () => {
    const innerValue = useMolecule(InnerMolecule);
    return <div data-testid="inner">Inner: {innerValue}</div>;
  };

  test("onUnmount not called when inner component is conditionally rendered", () => {
    const TestComponent = ({ showInner }: { showInner: boolean }) => (
      <OuterComponent>{showInner && <InnerComponent />}</OuterComponent>
    );

    const { rerender } = render(<TestComponent showInner={true} />);

    // Both molecules should be mounted initially
    outerMoleculeLifecycle.expectActivelyMounted();
    innerMoleculeLifecycle.expectActivelyMounted();

    // Hide the inner component
    rerender(<TestComponent showInner={false} />);

    outerMoleculeLifecycle.expectActivelyMounted();

    // BUG: Inner molecule should be unmounted, but it's not
    // Expected: innerMoleculeLifecycle.expectCalledTimesEach(1, 1, 1)
    // Actual: innerMoleculeLifecycle.expectCalledTimesEach(1, 1, 0) - unmount not called
    innerMoleculeLifecycle.expectCalledTimesEach(1, 1, 1);
  });
});
```

### PR DESCRIPTION
**Pull request by Wendystraite**
## Description of the change

Each molecule now has its own internal global scope instead of sharing one, allowing independent garbage collection even when other global molecules are still in use.

Fixes #80 

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation or Development tools (readme, specs, tests, code formatting)

### CODE REVIEW

File: src/vanilla/injector.ts [hunk 1]
```diff
@@ -703,7 +701,19 @@ function runMolecule(
...
+   * Create or reuse a unique internal global scope for this molecule.
+   * This ensures cleanup mechanisms work properly via the normal scope lifecycle.
+   */
+  if (!m[GlobalScopeSymbol]) {
+    const id = ++globalScopeId;
+    m[GlobalScopeSymbol] = createScope(Symbol(`bunshi.global.scope.${id}`), {
+      debugLabel: `Global Scope ${id}`,
+    });
+  }
+  trackingScopeGetter(m[GlobalScopeSymbol]);
```
Comment (loganvolkers) [inline src/vanilla/injector.ts]: Fix type errors to fix the build.

```suggestion
  trackingScopeGetter(m[GlobalScopeSymbol]!);
```
